= LÖVE for Newbies
A book about LÖVE, Games and Lua. image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/love2d-book/love2d-book?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

The collaborative book will be divided into three main units:

- A walkthrough to building a small prototype and introducing the user to the LÖVE framework,
- A more realistic revamp of the built prototype to create a "full" game, and lastly
- An area of examples and snippets containing best and known practices in game development.

== Metrics
. The three chapters are called __World__s and each section is a _Level_
. At the end of every _Level_, remind the reader about what he has learned in this chapter and show some practical issues that he can now solve
. Use examples and concrete language wherever possible. Programming is all about abstraction, and examples help make this a lighter and more enjoyable read
. Make everything interesting to read about and motivate the reader to keep on learning
. Be clear and direct when talking something new. Keep it simple, stupid!
. Every Level ends with additional exercises that the reader can choose to try
. Give “Pro Tips” and “Watch out!”-notices where fitting (Admonitions)
. Use informal language and short text to show new content

The book s written using a generator called Asciidoctor. +
Quick Reference: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

We have extended the AsciiDoctor syntax with "livecode" blocks and block macros. Use like this:

----
livecode::test[] // <1>

livecode::test[name=test2,preload="image1.png,image2.png"] // <2>

[livecode,example,preload=audio.wav] // <3>
++++
function love.draw()
    love.graphics.setColor( 255, 255, 0, 255 )
    love.graphics.rectangle( "fill", 10, 10, 100, 100 )
end
++++
----
<1> loads love2D-book-code/test directory
<2> load love2D-book/code/test directory and the assets called image1.png and image2.png. It's name is test2 so it doesn't conflict with the first.
<3> runs the code below it; has the name of "example" and loads audio.wav

Thank you for helping create this :)

