= LÖVE for Newbies
A book about LÖVE, Games and Lua.
:hardbreaks:
The collaborative book will be divided into three main units:

- A basic course to learn the principles and the syntax of Lua;
- A basic course to learn the fundamentals of creating games using the LÖVE framework;
- An area of examples and snippets containing best practices in game development.


== METRICS:
. All these main units we’ll call as “World”, and each chapter, as “Level”;
. At the end of every “Level”, we’ll remind the reader about what has been learned in this chapter and we’ll show some practical issues that now he will be able to solve;
. Examples, WE LOVE IT. Some computer books are extremely boring because they have various concepts released without practical examples. Examples make better understand something. Then examples will be widely used in the book.
. Make it clear that the reader is learning to do really interesting things. So they will feel more motivated to continue to understand the framework.
. Be clear and direct when talking something new. Keep stupidly simple.
. Every Level ends with additional exercises that the reader can choose to try
. Give “Pro Tips” and “Watch out!”-notices where fitting (Admonitions)
. Use informal language and short text to show new content.

The book s written using a generator called Asciidoctor.
Quick Reference: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

Welcome to collaborate with the project :D
