=== Basic Flow Concept

==== Flow
When we are in school, going through all those levels, we follow a simple study sequency. Basic concepts are learned at the beginning of our school life and more complex subjetcts (which depend on the most basic) are learned ahead.
Write code works in a similar way. We follow the same order, that is, before we try to do complex things, we have to talk to the computer how to do them.
A code is understood by the computer from the first to the last line. If  we ask the computer to calculates powers but do not teach it how to make a multiplication, probably it will not solve our problem.

==== Conditions
We can tell the computer that it chooses other paths and jump some lines.
Think that you are lost in a field and reaches a point in front there are two possible paths. You will choose one of them by some condition. In computer programming, this concept is called *conditional structure*.

==== Loops
It is our usual to repeat the same idea to perform a larger task. If I ask you to make 8 cookies, you will follow a bunch of steps for each cookie to complete 8 cookies. This concept is called *loop*.

