=== Storing Data in Variables
And now we begin the fun part ..

We have spoken that the computer can make various tasks using some instructions. Let's know the first key concept, *the variable*.

When you make the cookies, you use few *ingredients* and some *tools*. Let's start with the ingredients, which for computing, are called variables.

The computer is a mathematical machine that performs tasks from data. Variables are a space that we allocate in the computer memory to store data that will be useful for us.

For example:
[source, lua]
----
name = "Joseph"
age = 18
print (name)
----

In this small piece of code we are assigning the word "Joseph" to the variable *name* and 18 to the variable *age*. We use this syntax in Lua to allocate space in memory. In the left side of the equal symbol specify the variable name and the right hand, the data. The last line tells the computer that it should show the data contained in the variable name. _print_ is a *tool* from Lua. The language have a lot of useful tools. Test and see the result.

How about trying to make the computer show the buddy's age?

