[[world1-2]]
=== The Tools
==== LÖVE
So, what makes a LÖVE Project? +
At core a LÖVE Project is just a folder containing everything needed to make the game;
Code, Images, Sound and Video files and everything else you might need.


===== Code
Obviously, a game contains code. LÖVE Games are programmed in Lua, which you should be familiar with already.
Generally Lua Source Files (`.lua`) can lay around anywhere in the project
directory and have arbitrary names... except for two special ones:
* main.lua
* conf.lua

These two are the only files that the LÖVE Framework runs; they are the starting
points of every game or project you build.

===== main.lua
As the name implies this file will contain all your *main code* - what exactly
that will be and how you organize your code is up to you.
Usually this file contains the used _Callback Routines_, which will be covered in <<world1-3, the next Level>>.
For smaller projects and the next levels in this book this will be the only file
(except for `conf.lua`) you will need.

===== conf.lua
_conf_ is short for **Conf**iguration, and thats what `conf.lua` is all about.
You can fill this file with a function called `love.conf( t )` that accepts a table as it's only parameter.
In that function you can then modify certain fields of the table and thereby
change the configuration the LÖVE Framework uses when it first creates your window.

Here is a function that sets every possible value to it's default value - and thereby does nothing:

.Full `conf.lua` example
[source,lua]
----
function love.conf(t)
    t.identity = nil                   -- The name of the save directory (string)
    t.version = "0.9.1"                -- The LÖVE version this game was made for (string)
    t.console = false                  -- Attach a console (boolean, Windows only)

    t.window.title = "Untitled"        -- The window title (string)
    t.window.icon = nil                -- Filepath to an image to use as the window's icon (string)
    t.window.width = 800               -- The window width (number)
    t.window.height = 600              -- The window height (number)
    t.window.borderless = false        -- Remove all border visuals from the window (boolean)
    t.window.resizable = false         -- Let the window be user-resizable (boolean)
    t.window.minwidth = 1              -- Minimum window width if the window is resizable (number)
    t.window.minheight = 1             -- Minimum window height if the window is resizable (number)
    t.window.fullscreen = false        -- Enable fullscreen (boolean)
    t.window.fullscreentype = "normal" -- Standard fullscreen or desktop fullscreen mode (string)
    t.window.vsync = true              -- Enable vertical sync (boolean)
    t.window.fsaa = 0                  -- The number of samples to use with multi-sampled antialiasing (number)
    t.window.display = 1               -- Index of the monitor to show the window in (number)
    t.window.highdpi = false           -- Enable high-dpi mode for the window on a Retina display (boolean). Added in 0.9.1
    t.window.srgb = false              -- Enable sRGB gamma correction when drawing to the screen (boolean). Added in 0.9.1

    t.modules.audio = true             -- Enable the audio module (boolean)
    t.modules.event = true             -- Enable the event module (boolean)
    t.modules.graphics = true          -- Enable the graphics module (boolean)
    t.modules.image = true             -- Enable the image module (boolean)
    t.modules.joystick = true          -- Enable the joystick module (boolean)
    t.modules.keyboard = true          -- Enable the keyboard module (boolean)
    t.modules.math = true              -- Enable the math module (boolean)
    t.modules.mouse = true             -- Enable the mouse module (boolean)
    t.modules.physics = true           -- Enable the physics module (boolean)
    t.modules.sound = true             -- Enable the sound module (boolean)
    t.modules.system = true            -- Enable the system module (boolean)
    t.modules.timer = true             -- Enable the timer module (boolean)
    t.modules.window = true            -- Enable the window module (boolean)
    t.modules.thread = true            -- Enable the thread module (boolean)
end
----

[NOTE]
You don't need to use a `conf.lua` or specify every key in the conf table;
everything you leave out will remain at it's default value.

You will mostly be using this to set a different resolution for your game and set the game title.

.Usual `conf.lua`
[source,lua]
----
function love.conf( t )
    t.identity      = "GtGLG"
    t.version       = "0.9.1"

    t.window.title  = "Gary, the green-legged Giraffe"
    t.window.width  = 1200
    t.window.height = 720

    t.window.fsaa   = 4
    t.window.vsync  = true
end
----

===== Other files
Everything else will need to be ``require``d by `main.lua` in some way (direct or indirect).


===== Images, Animations, Sounds and other Assets
All of these files need to be somewhere in the project directory aswell.
You will learn to load and draw or play these files throughout this World.


Even though you can just have all the files in one directory, it is advised that
you structure your files in a logical hierarchy, for example like this:

....
- mygame/
    + main.lua
    + conf.lua
    + lib/
        + library1.lua
        + library2.lua
        + sometool.lua
    + assets/
        + images/
            + player.png
            + rock.png
        + sounds/
            + impact.wav
            + menumusic.mp3
        + videos/
            + intro.mp4
....
