[[world1-3]]
=== Starting Small

Alright, now that we now the file structure, we can get started on the actual code.

==== Drawing Circles
In the <<world1-2, last Level>> we learned that our main code goes in a file called
`main.lua` and that we are supposed to define _Callback Routines_ there.

A _Callback Routine_ is nothing but a function with a specific name the LÖVE framework knows.
For example, whenever a key is pressed, LÖVE will attempt to call a function called `love.keypressed`.
If you have not written than function (yet), the keypress will be ignored, but
if you choose to write one, you can do something in reaction to that _Event_.

One of the most important Callbacks is `love.draw`.
As the name implies, this is where any drawing to the screen should take place.

.main.lua
[source,lua]
----
function love.draw()
  -- draw a sparkling unicorn
end
----

Inside this function we can now draw everything we want the player to be able to see.
To get started, let's draw a circle.
To draw a circle, we will use the function wiki:love.graphics.circle[].
Go and see what you can find on the wiki page now!

[NOTE]
--
https://love2d.org/wiki/love[The wiki] is *the* most important resource for programming in LÖVE.
You can find information and examples for all available functions there.

When you get stuck somewhere, first consult the wiki.
If you cannot find a solution there, *search the forum*. If you _still_ do not find anything,
start a new thread in the *Support & Development* forum.
Provide a clear, concise title and _be patient!_
--

As you can see, `love.graphics.circle` accepts five parameters:

- mode, whether to _fill_ or _stroke_ the circle (`"line"` is used to stroke)
- x, the horizontal position of the circle's center
- y, the vertical position
- radius, the circle's radius (half of the width)
- segments, how detailed to draw the circle. This can be left out.

So, to draw a filled 30px circle at (100, 100) and then a stroked one 20px further down,
this is what we need to do:

.main.lua
[source,lua]
----
function love.draw()
  love.graphics.circle("fill", 100, 100, 15)
  love.graphics.circle("line", 100, 120, 15)
end
----

[livecode,circles]
++++
function love.draw()
  love.graphics.circle("fill", 100, 100, 15)
  love.graphics.circle("line", 100, 120, 15)
end
++++

Quite similarly, we can also draw rectangles using wiki:love.graphics.rectangle[].
The six parameters are:

- mode, same as for `circle`
- x, this time it is not the center position of the top-left corner
- y, again, relative to the top left corner
- width, the width of the rectangle being drawn
- height, the height of the rectangle

Another function you will use in probably every game is wiki:love.graphics.setColor[].
It accepts three numbers in the range of `0` to `255`, specifying the intensity
of red, green and blue respectively.
A fourth value, used as alpha (transparency) can optionally be supplied.

The last drawing function for now is wiki:love.graphics.line[].
You can pass it four values, each representing the x and y values of a point.

Putting it all together, we can draw a little stickman:

[source,lua]
----
function love.draw()
  love.graphics.setColor(0, 0, 0)                 -- black
  love.graphics.line(40, 80, 35, 100)             -- left foot
  love.graphics.line(40, 80, 35, 100)             -- right foot

  love.graphics.setColor(0, 255, 0)               -- green
  love.graphics.rectangle("fill", 30, 30, 40, 60) -- body

  love.graphics.setColor(255, 0, 0)               -- red
  love.graphics.circle("fill", 50, 20, 15)        -- head
end
----

[livecode,stickman]
++++
function love.draw()
  love.graphics.setColor(255, 255, 255)           -- white
  love.graphics.line(40, 80, 35, 100)             -- left foot
  love.graphics.line(40, 80, 35, 100)             -- right foot

  love.graphics.setColor(0, 255, 0)               -- green
  love.graphics.rectangle("fill", 30, 30, 40, 60) -- body

  love.graphics.setColor(255, 0, 0)               -- red
  love.graphics.circle("fill", 50, 20, 15)        -- head
end
++++

[NOTE]
Note how the head is in front of and the feet are behind the body
because of the order we chose to draw them in.
