[[world1-4]]
=== Creating Motion
<<world1-3, Last time>> we managed to draw a terrible-looking stickman,
but he seemed rather... lifeless.
If we want to make a game, it might be a good idea to have things moving around.

==== A Ship
As we are working towards an Asteroids clone, let's start out with a spaceship.
Before we can make a spaceship move, we need a spaceship though:

.main.lua
[source,lua]
----
function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", 20, 20, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(70, 30, 120, 30)
end
----

[livecode,1-4-ship]
++++
function love.draw()
  love.graphics.setColor(200, 200, 200)
  love.graphics.rectangle("fill", 20, 20, 100, 20)
  love.graphics.setColor(80, 80, 80)
  love.graphics.line(70, 30, 120, 30)
end
++++

I know, I know, that doesn't look very aerodynamic.
But I'll tell you what, there's no air resistance in space anyway -
at least there's a line to indicate which direction we are facing.

==== An Engine
Alright, so how do we make this thing move?
We will obviously need a variable to keep track of it's current position.
In fact we will be using two, one for each coordinate we are going to simulate the ship on:

.main.lua
[source,lua]
----
x, y = 20, 20

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", x, y, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(x+20, y+10, x+100, y+10)
end
----

Now we only need to change the values of `x` and `y` and the ship will follow.
We could for example make them always point to the current mouse position:

.main.lua
[source,lua]
----
x, y = 20, 20

function love.update(dt)
  x, y = love.mouse.getPosition()
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", x, y, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(x+20, y+10, x+100, y+10)
end
----

[livecode,1-4-mousecontrol]
++++
x, y = 20, 20

function love.update(dt)
  x, y = love.mouse.getPosition()
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", x, y, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(x+20, y+10, x+100, y+10)
end
++++

Wait, what happened here?
First of all, I introduced a new LÖVE callback: wiki:love.update[].
As the name implies, this is where we _update_ the current game state.
wiki:love.update[] is where things _happen_; This is where the player moves,
the enemies shoot and the lighting is calculated.
One thing you might notice immediately is that unlike wiki:love.draw[],
wiki:love.update[] receives a parameter: `dt`.

`dt` is short for **d**elta**time** (_time difference_).
`dt` is always the time (in seconds) since the last time wiki:love.update[] was called.
In this small example `dt` is not used, but it is very useful, as we will see later on.

Secondly, another LÖVE function has come into play: wiki:love.mouse.getPosition[].
It should again be rather obvious what this function is doing for us;
it returns the mouse's current position along the x and y axis (in pixels).

Alright, now things are moving, but in our game we don't want the ship to be
controlled by the mouse.
Also, with the current code players with a faster mouse would have an advantage,
they could move around much more quickly.
Instead, let's introduce a fixed speed for our spaceship, and add keyboard controls:

.main.lua
[source,lua]
----
player = {
  x = 20,
  y = 20
}

SPEED = 300

function love.update(dt)
  if love.keyboard.isDown"right" then
    player.x = player.x + SPEED*dt
  end
  if love.keyboard.isDown"left" then
    player.x = player.x - SPEED*dt
  end
  if love.keyboard.isDown"down" then
    player.y = player.y + SPEED*dt
  end
  if love.keyboard.isDown"up" then
    player.y = player.y - SPEED*dt
  end
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", player.x, player.y, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(player.x+20, player.y+10, player.x+100, player.y+10)
end
----

[livecode,1-4-keyboard]
++++
player = {
  x = 20,
  y = 20
}

SPEED = 300

function love.update(dt)
  if love.keyboard.isDown("right") then
    player.x = player.x + SPEED*dt
  end
  if love.keyboard.isDown("left") then
    player.x = player.x - SPEED*dt
  end
  if love.keyboard.isDown("down") then
    player.y = player.y + SPEED*dt
  end
  if love.keyboard.isDown("up") then
    player.y = player.y - SPEED*dt
  end
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.rectangle("fill", player.x, player.y, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(player.x+20, player.y+10, player.x+100, player.y+10)
end
++++

Great, let's go through the changes:
You can immediately see that `x` and `y` have disappeared,
instead there is now a table called `player.`
`player` stores the position under the keys `"x"` and `"y"`,
so nothing has really changed except the varible names are longer,
but I have done this so our code stays readable as we progress;
As we add enemies and bullets we will need to keep track of a lot more `x`s and `y`s.

As we can see, I have also added a new variable called `SPEED`.
`SPEED` is never changed in the code, so I could've also replaced every occurence
further down with it's value, `300` right away.
However keeping it at the top like this makes it easy to modify the speed,
also I cannot forget to modify it in all the places should I change it some time.
`SPEED` is uppercased because I use this style to name constant values,
but this is just a stylistic choice by me.

Now on to the actual keyboard code!
There is another new LÖVE function used here: wiki:love.keyboard.isDown[].
Once again the name should make the purpose of the function very clear,
you should start to see a pattern here.
wiki:love.keyboard.isDown[] checks if the key given is down.
In LÖVE keys are identified by a string,
in this example we are using `"up"`, `"down"` etc., but there are many more.
You can view a table of all the keys on the wiki: wiki:KeyConstant[].

Using `if` and wiki:love.keyboard.isDown[] we add or substract `SPEED * dt` from the fitting coordinates,
when the _left_ key is pressed, we substract from `player.x`;
when _down_ is pressed we add to the y-coordinate.

Now, why do we multiply `SPEED` with `dt`?
As I said above, the time step between each wiki:love.update[] execution may vary;
for example a scene that has to draw a lot of enemies might take longer do draw
than one that just features a few.
Other factors like the power of the graphics card and processor
or how busy the computer is with other things might also impact the updaterate.

It is important that we care about this,
a game that runs twice as fast on better hardware is unacceptable.
By multiplying with `dt` we can scale the speed by the time that we are actually simulating.

[NOTE]
This means we are also always "lagging a frame behind" in update-time,
but that doesn't really make a difference in practice.

Because `dt` is measured in seconds, it also makes specifying movement speeds
etc. very convenient, `SPEED` is now measured in *pixels per second*. This gives
it a workable size and something you can think about; if we had not used `dt` we
would have to deal with tiny values in *pixels per frame*.
