[[world1-5]]
=== Better Steering
Great, so now we can fly around!
A little realism would be nice though, spaceships don't really fly like that.
It is time too look back to <<world1-1-spaceship, World 1-1>> and look at our notes for the spaceship:

[quote,"World 1-1, The Spaceship"]
____
The spaceship is the main thing the player can control in our game.
The player can use two keys to accelerate or decelerate in the direction the ship
is currently facing. He can also turn the spaceship with two other keys.
Lastly the player can press a button to fire a shot.

When the spaceships leaves the screen on one side, it will enter from the opposite side,
keeping its velocity.

We can see that the spaceship needs to have a `position`, `velocity` and `rotation`.
in <<world1-4, World 1-5>> we will see that the actual way of saving the information
we use differs, but we could as well do with this "definition".
____

Okay, so let's get to work:

code_example::world1/05_better-steering/rotation[]
livecode::world1/05_better-steering/rotation[]

Okay, some changes.
We now store values for `xvel`, `yvel` and `rotation` in our `player` table.
`x` and `y` are still used to track the current position, but our wiki:love.draw[] has changed,
`x` and `y` now refer to the center of the spaceship.
This is important so that the rotation looks realistic and the physics we introduce later work as expected.

To draw the spaceship, we now use two new functions:
wiki:love.graphics.translate[] and wiki:love.graphics.rotate[].

Using them is pretty straight-forward, wiki:love.graphics.translate[]
moves everything that is drawn after it is called by the amount in `x` and `y`,
wiki:love.graphics.rotate[] rotates everything around the current point (0,0).
These two functions are called *transformation functions* because they *transform*
everything that is drawn afterwards. There are some more, like wiki:love.graphics.scale[],
but these will do for now.

Note the order in which we call them, it is very important for the correct result!
You can try this by yourself: starting from the same point,
try rotating 90° to the left, then walking two steps,
then do those two movements in the opposite order.
You will end up in two different places.

Our new wiki:love.update[] is also really simple for now, we just modify `rotation`.
I have introduced a new constant `ANGACCEL` (**ang**ular **accel**eration).
This is the angle that it should turn per second, note the use of `dt`,
just like in <<world1-4, World 1-4>>.

Okay, so what about `xvel` and `yvel`? I skipped the actual __move__ment above,
but those are the **vel**ocities along the x- and y-axis.
We will store them seperately so that the player can drift around
(if we only stored the total velocity and assumed that it was always pointing
the same way the ship does then it would behave more like a car, with full traction).

To implement those two left-out pieces of code we need some very basic trigonometry.
When the `up` key is pressed, we want to add velocity in the direction the ship
is currently pointing. When we press `down` the opposite should happen.

We will need to use `math.sin` and `math.cos` to calculate the parts of the
acceleration that apply to each axis, based on the angle the ship is rotated to:

code_example::world1/05_better-steering/momentum[]

[NOTE]
Note how again `ACCELERATION` is multiplied by `dt` before being scaled by
`math.cos` and `math.sin` for the corresponding axis.

This already feels a lot like Asteroids!

livecode::world1/05_better-steering/momentum[]
