[[world1-5]]
=== Better Steering
Great, so now we can fly around!
A little realism would be nice though, spaceships don't really fly like that.
It is time too look back to <<world1-1-spaceship, World 1-1>> and look at our notes for the spaceship:

[quote,"World 1-1, The Spaceship"]
The spaceship is the main thing the player can control in our game.
The player can use two keys to accelerate or decelerate in the direction the ship
is currently facing. He can also turn the spaceship with two other keys.
Lastly the player can press a button to fire a shot.

When the spaceships leaves the screen on one side, it will enter from the opposite side,
keeping it's velocity.

We can see that the spaceship needs to have a `position`, `velocity` and `rotation`.
in <<world1-4, World 1-5>> we will see that the actual way of saving the information
we use differs, but we could as well do with this "definition".

Okay, so let's get to work:

.main.lua
[source,lua]
----
player = {
  x = 50,
  y = 50,
  xvel = 0,
  yvel = 0,
  rotation = 0
}

local ACCELERATION =  20

function love.update(dt)
  if love.keyboard.isDown"right" then
    -- rotate clockwise
  end
  if love.keyboard.isDown"left" then
    -- rotate counter-clockwise
  end
  if love.keyboard.isDown"down" then
    -- decelerate / accelerate backwards
  end
  if love.keyboard.isDown"up" then
    -- acellerate
  end
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.translate(player.x, player.y)
  love.graphics.rotate(player.rotation)
  love.graphics.rectangle("fill", -50, -10, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(20, 0, 50, 0)
end
----

[livecode,1-4-keyboard]
++++
player = {
  x = 150,
  y = 150,
  xvel = 0,
  yvel = 0,
  rotation = 0
}

local ANGACCEL      = 4
local ACCELERATION  = 20

function love.update(dt)
  if love.keyboard.isDown"right" then
    -- rotate clockwise
    player.rotation = player.rotation + ANGACCEL*dt
  end
  if love.keyboard.isDown"left" then
    -- rotate counter-clockwise
    player.rotation = player.rotation - ANGACCEL*dt
  end
  if love.keyboard.isDown"down" then
    -- decelerate / accelerate backwards
    -- (left out for now)
  end
  if love.keyboard.isDown"up" then
    -- acellerate
    -- (left out for now)
  end
end

function love.draw()
  love.graphics.setColor(80, 80, 80)
  love.graphics.translate(player.x, player.y)
  love.graphics.rotate(player.rotation)
  love.graphics.rectangle("fill", -50, -10, 100, 20)
  love.graphics.setColor(200, 200, 200)
  love.graphics.line(20, 0, 50, 0)
end
++++

Okay, a few changes.
We now store values for `xvel`, `yvel` and `rotation` in our `player` table.
`x` and `y` are still used to track the current position, but our wiki:love.draw[] has changed,
`x` and `y` now refer to the center of the spaceship.
This is important so that the rotation looks realistic and the physics we introduce later work as expected.

To draw the spaceship, we now use two new functions:
wiki:love.graphics.translate[] and love.graphics.rotate[].

Using them is pretty straight-forward, wiki:love.graphics.translate[]
moves everything that is drawn after it is called by the amount in `x` and `y`,
wiki:love.graphics.rotate[] rotates everything around the current point (0,0).
These two functions are called *transformation functions* because they *transform*
everything that is drawn afterwards. There are some more, like wiki:love.graphics.scale[],
but these will do for now.

Note the order in which we call them, it is very important for the correct result!
You can try this by yourself: starting from the same point,
try rotating 90° to the left, then walking two steps once, then the other way around.
You will end up in two different places.

Our new wiki:love.update[] is also really easy for now, we just modify `rotation`.
I have introduced a new constant `ANGACCEL` (**ang**ular **accel**eration),
this is the angle that it should turn per second, note the use of `dt`,
just like in <<world1-4, World 1-4>>.

Okay, so what about `xvel` and `yvel`? I skipped the actual __move__ment above,
but those are the **vel**ocities along the x- and y-axis.
We will store them seperately so that the player can drift around.
